### PR TITLE
feat(marker): enable ng-click handling

### PR DESCRIPTION
**Pull request by polesapart**
Revised from #252  following orientations from @juristr

### CODE REVIEW

**Comment by juristr** [comment]
@polesapart Awesome :+1:. Theoretically you could have also submitted it directly to your previous branch, using `git push --force` on that branch. But yea, use `--force` with caution :wink: 

image

have a nice weekend ahead and thx for contributing!

**Comment by polesapart** [comment]
@juristr You're welcome. And I'm kind of a git illiterate!

**Comment by juristr** [comment]
@polesapart Oh well, don't worry. I learnt about squashing and git rebase in the very same way, through a PR on GitHub :)

**Comment by ubermanu** [comment]
Hello, I just noticed `ng-click` does not work if marker label is not defined
Example: http://jsfiddle.net/2jykzcxk/

**Comment by juristr** [comment]
@polesapart Could you take a look at what @ubermanu reported? thx :+1:

**Comment by polesapart** [comment]
I'm traveling but should be back in a few days and I'll look into it. Thanks for reporting

**Pull request merged**
