### PR TITLE
Enable ng-click handling for marker directive

### PR DESCRIPTION
**Pull request by polesapart**

### CODE REVIEW

**Comment by polesapart** [comment]
For discussion, see notes on issue #76 . The onClick implementation seems to interact badly with label handling. Instead of fixing that, it seemed natural to make it look a little more "angularized".

**Comment by juristr** [comment]
@polesapart Awesome, LGTM. Could you just squash your commits to have a nice single commit "(feat) Instead of dedicated handler, pass click event to angular do...." ? That'd be awesome, so I can merge this in.

Thanks a lot for contributing :+1:

**Comment by polesapart** [comment]
@juristr  Sorry for the delay. I didn't get what you're asking me to do, could you elaborate? Thanks!

**Comment by juristr** [comment]
Hi, no worries. I meant to polish your git commit history you submitted here, by doing a rebase and squash useless/wrong commits:
image

:wink:. This is usually considered best practice when submitting PRs.

I wrote a post about how to do it properly: http://juristr.com/blog/2013/04/git-explained/#Polishingyourfeaturebranchcommits  
Otherwise if you search on [google for squashing or interactive rebase you should find plenty of resources explaining how to do it](https://www.google.it/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=git%20squash%20commits).

I think your commit could be "squashed" into a single one named like

```
feat(marker): enable ng-click handling
```

Or something similar. I do care a lot about nice commit messages because there's [an automatism behind](http://juristr.com/blog/2015/10/release-like-a-pro/) that uses them to determine the next semantic version of the package and build the [release log](https://github.com/tombatossals/angular-openlayers-directive/releases).

Hope this helps, otherwise simply let me know :wink:

**Comment by tatianass** [comment]
Do you have an example as how this works? I tried and tried and nothing seems to work.

**Pull request closed without merging**
