### PR TITLE
Feature/update openlayers 4.3.4

### PR DESCRIPTION
**Pull request by mfdev1**
Upgrade openlayers to 4.3.4
* fix for Safari on iOS 11 (since 4.3.4)

### CODE REVIEW

**Comment by ZorbaDimatteo** [comment]
Hello! 
I've started a new project using webpack, but I'm having problems with ol3. So I suppose this pull request will solve some problems :)

**Comment by juristr** [comment]
@mfdev1 Is this a breaking change? Like for others, they'd have to upgrade their ol dependency to v4 from v3, which I suppose could break some stuff. I guess we should therefore release this a s a major version bump. What do you think?

**Comment by mfdev1** [comment]
@juristr 

Hello.
ol has many breaking changes, but my project has not raised a big problem.
but care must be taken in that it is fractional zoom level in ol v3.20.0

ol version has been changed from v3 to v4, we think that major version up is good as well.

**Comment by v1r0x** [comment]
I think about switching from Leaflet to OL in an (obviously) angular project. I'd like to go with the latest (>= 4.x) OL release. Do you have any plans to release a new major version soon?

**Comment by jousepo** [comment]
Hi!!! Will this update merge into master branch someday¿?¿? Seems that can be fast-forwarded but there is no changes since 3 months

**Comment by juristr** [comment]
@jousepo Hey, sorry, I know. I've been in involved in lots of other things lately. I'll check whether I can release a `v2.0.0` containing this update

**Comment by juristr** [comment]
ok, just merged this in and released `v2.0.0`: https://github.com/tombatossals/angular-openlayers-directive/releases/tag/v2.0.0

**Pull request closed without merging**
