### PR TITLE
Fix style issues that prevented grunt build

### PR DESCRIPTION
**Pull request by ageblade**
Mostly line breaks and some indent
Also updated protractor selenium version

### CODE REVIEW

**Comment by tombatossals** [comment]
Thanks @ageblade

**Comment by ageblade** [comment]
For some reason now the jscs fails again in my machine after pulling the latest from master branch.
I think it has something to do with line endings (CRLF/LF etc..) 

Any clue about that ?

**Comment by dmishne** [comment]
workaround it with git config core.autocrlf false.
Similar thread: https://github.com/ramda/ramda/issues/468

**Comment by juristr** [comment]
:+1:

**Pull request merged**
