### PR TITLE
feat(build): Added the travis CI file and the semantic-release dependency to NPM

### PR DESCRIPTION
**Pull request by tombatossals**
Finished the semantic-release setup process, this commit adds the required files to integrate our library with it.

### CODE REVIEW

**Comment by juristr** [comment]
@tombatossals Awesome! I'll check and do what's left, till finally merging in the ol v3.6+ compatibility branch mentioned in #155 

Meanwhile, thx! :+1:

**Comment by tombatossals** [comment]
Great, we need increment the major version just now, I'm with you that we need to be in sync with the actual OpenLayers release.

I'm unable to pass the tests on travis in the PR, but in local they work great, I'm taking a look at this.

**Comment by tombatossals** [comment]
Ok, I finally solved this.

@juristr if you want to merge this PR, from now on the travisCI compilations will pass ok.

**Comment by juristr** [comment]
@tombatossals cool, I'll give it a go tonight after work. Thx!

**Comment by juristr** [comment]
@tombatossals Done!! We're now officially publishing using semantic-release:

- https://github.com/tombatossals/angular-openlayers-directive/releases
- https://www.npmjs.com/package/angular-openlayers-directive

Every new push to master is automatically released with semantic-release. My merge of #155 will then mark v1.0.0.

**Pull request closed without merging**
