### PR TITLE
fix(layer.js): remove unnecessary returns, to more-gracefully watch l…

### LINKED ISSUE #336: Logic around properties $watch prevents source update if opacity AND visible are not set.
## Overview 

The following user case will create a situation where a GeoJson layer does not update it's source when expected. 

## Use case 

Consider the following use case: 

```
<openlayers width="100%" height="450px">
  <ol-layer ng-if="vm.geoJson.source.geojson" ol-layer-properties="vm.geoJson"></ol-layer>
</openlayers>

function setAndUpdateGeoJson(data) {
  vm.geoJson = {
    name: 'A Geo Layer',
    source: {
      type: 'GeoJSON',
      geojson: {
        object: data
      }
    }
  };
}

setAndUpdateGeoJson(<FeatureCollection 1>)

setAndUpdateGeoJson(<FeatureCollection 2>)
```

## Expected behavior  

The map updates with the new GeoJson source.

## Actual behavior

The map does not update. 

## Why? 

This happens because of the [logic around how properties are watched](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/layer.js#L62-L75). When the watch callback fires, Openlayers directive first checks if two properties (`opacity` and `visible`) are defined. If `visible` is not defined, it's set to default value `true` and the watch callback returns, preventing any layer creation of updating. Since the properties object is now modified, the watcher fires again, and this time the callback checks if `opacity` is defined. If not, again it's set to default value `1` and returned early. The properties watcher now fires a 3rd time. 

The problem is that now the watcher callback arguments, `oldProperties` and `newProperties`, now have the same `source`, and the [logic here](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/layer.js#L137) `if (isDefined(oldProperties) && !equals(properties.source, oldProperties.source)) {` evaluates to true, preventing the layer from being updated. 

## How to fix option 1 

Set opacity and visible properties explicitly. 

```
function setAndUpdateGeoJson(data) {
  vm.geoJson = {
    name: 'A Geo Layer',
    visible: true,
    opacity: 1,
    source: {
      type: 'GeoJSON',
      geojson: {
        object: data
      }
    }
  };
}
```

## How to fix option 2 

Break out the set and update function.  

```
function setGeoJson(data) {
  vm.geoJson = {
    name: 'A Geo Layer',
    source: {
      type: 'GeoJSON',
      geojson: {
        object: data
      }
    }
  };
}

function updateGeoJson() {
  vm.geoJson.source.geojson = data;
}
```

## What to do ?

I'm not actually sure this is a bug, it's more of a gotcha which I wanted to document for others who encounter it. 

That being said, is it necessary to have the returns [here](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/layer.js#L69) and [here](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/layer.js#L74)? Seems like removing them would still work and would prevent this issue.

### PR DESCRIPTION
**Pull request by coltonbrugger**
…ayer property changes

Resolves #336

### CODE REVIEW

**Comment by juristr** [comment]
🤔 going to check this tomorrow on my codebase to verify nothing breaks. Actually I'm not quite sure why these return statements are in there. They have been there already when I took over maintenance of this project 😄. Thx for ur PR

**Comment by juristr** [comment]
@aagg1234 Could you maybe try to include these mods in our codebase to verify it doesn't break anything?

**Comment by coltonbrugger** [comment]
Sorry, accidentally brough additional commits (related to other fixes and openlayers version upgrades). I'm not sure how to roll those back here. Let me know how to best handle.

**Comment by juristr** [comment]
See #389

**Pull request closed without merging**
