### PR TITLE
Layer clustering

### PR DESCRIPTION
**Pull request by claustres**
Related to issue #86

### CODE REVIEW

**Comment by claustres** [comment]
I just noticed that I forgot to add a link to the new example in the README, sorry. Do you want a new pull request for that ?

**Comment by tombatossals** [comment]
Great addition @claustres, thanks!!

**Comment by marloncarvalho** [comment]
It's an amazing addition. I was looking for it a while and didn't know this directive supported this feature. So please remember to add an example in the README.

**Comment by juristr** [comment]
@marloncarvalho Sure, you're right. @claustres Could you send another PR linking your addition in the README? That'd be awesome, thx!

**Pull request merged**
