### PR TITLE
fix(olHelpers.js, layersSpec.js): passing projection code instead of …

### PR DESCRIPTION
**Pull request by sathishatnet**
…projection object, while converting the geojson data to vector feature for fixing the issue (#295)

### CODE REVIEW

**Comment by juristr** [comment]
@sathishatnet going to try this fix against our codebase on Monday. Would be cool to have a unit test for this as well to prevent regressions.

**Comment by sathishatnet** [comment]
Sure let me, write some unit test to cover this scenario

**Comment by juristr** [comment]
@sathishatnet You can find some tests in here already: https://github.com/tombatossals/angular-openlayers-directive/tree/master/test/unit.

thx

**Comment by sathishatnet** [comment]
@juristr , Already modified the existing test case, to validate the scenario

**Comment by juristr** [comment]
@sathishatnet Ah ok, perfect. Going to merge it.

**Pull request merged**
