### PR TITLE
adds check for the 'setStyle' method

### PR DESCRIPTION
**Pull request by aagg1234**
@juristr 

adds check for the 'setStyle' method

### CODE REVIEW

**Comment by elec29a** [comment]
great :)

**Comment by juristr** [comment]
:thumbsup: will give it a look later. Thx!

**Comment by tombatossals** [comment]
Hi @aagg1234, @juristr, it looks great to me. 

@juristr, I'm merging it, just tell me if you think opposite.

**Comment by juristr** [comment]
@tombatossals :+1: @aagg1234 and @elec29a are part of my team, so the fix should be fine :smile:

Thx for merging. I'm currently in holiday so things are moving a bit more slowly :wink:

**Pull request merged**
